version: '3.4'

services:

  launcher:
    image: server.launcher
    container_name: tg.run
    networks:
      - tg-server
    environment:
      OPENTTD_VERSION: "12.1"
      OPENGFX_VERSION: "7.1"
      PATH: "/home/openttd/run:$PATH"
      RCON_PASSWORD: "xxx"
      ADMIN_PASSWORD: "xxxx"
      CLIENT_NAME: "vanilla"
      SERVER_NAME: "TG Vanilla (Reddit legacy)"
    ports:
      - 3979:3979
      - 3977:3977
    build: .
  
networks:
  tg-server:
    name: tg-server.network