version: '3.4'

services:

  builder:
    image: server.builder
    container_name: tg.builder
    networks: 
      - tg-server
    build:
      context: .
      dockerfile: server.builder/Dockerfile
  
  vanilla:
    image: server.vanilla
    container_name: tg.vanilla
    depends_on:
      - builder
    networks:
      - tg-server
    ports:
      - 3979:3979
      - 3977:3977
    environment:
      - V_RCON_PASSWORD=******
      - V_ADMIN_PASSWORD=******
    build:
      context: .
      dockerfile: server.vanilla/Dockerfile
  
  welcome:
    image: server.welcome
    container_name: tg.welcome
    depends_on:
      - builder
    networks:
      - tg-server
    ports:
      - 3982:3982
      - 3977:3977
    environment:
      - W_RCON_PASSWORD=******
      - W_ADMIN_PASSWORD=******
    build:
      context: .
      dockerfile: server.welcome/Dockerfile
  
networks:
  tg-server:
    name: tg-server.network