version: '3.4'

services:

  vanilla:
    image: server.vanilla
    container_name: tg.vanilla
    networks:
      - tg-server
    ports:
      - 3982:3982
      - 3977:3977
    environment:
      - V_RCON_PASSWORD="*"
      - V_ADMIN_PASSWORD="*"
    build:
      context: .
      dockerfile: server.vanilla/Dockerfile
  
  welcome:
    image: server.welcome
    container_name: tg.welcome
    networks:
      - tg-server
    ports:
      - 3979:3979
      - 3972:3972
    environment:
      - W_RCON_PASSWORD="*"
      - W_ADMIN_PASSWORD="*"
    build:
      context: .
      dockerfile: server.welcome/Dockerfile
  
  public:
    image: server.public
    container_name: tg.public
    networks:
      - tg-server
    ports:
      - 3980:3980
      - 3970:3970
    environment:
      - P_SERVER_PASSWORD="*"
      - P_RCON_PASSWORD="*"
      - P_ADMIN_PASSWORD="*"
    build:
      context: .
      dockerfile: server.public/Dockerfile
  
networks:
  tg-server:
    name: tg-server.network