#!usr/bin/env bash

echo "Building server image..."
    docker build -t vanilla.build . &&

echo "Starting server ..."
    exec docker run -it --rm \
    -p 3982:3982/udp -p 3982:3982/tcp -p 3977:3977/tcp \
    -v /tmp/tg-vanilla.server:/config:rw \
    --name TG_Vanilla.server vanilla.build
exit 0